import {
  Binary,
  Braces,
  CaseSensitive,
  Clock3,
  Eye,
  FileCode,
  FileJson,
  FileSearch,
  Fingerprint,
  KeyRound,
  LinkIcon,
  MapPinned,
  Palette,
  Paintbrush,
  Regex,
  Ruler,
  ShieldCheck,
} from 'lucide-react';

export const toolCategories = [
  { id: 'all', label: '全部' },
  { id: 'conversion', label: '转换' },
  { id: 'encoding', label: '编码' },
  { id: 'formatting', label: '格式化' },
  { id: 'css', label: 'CSS' },
  { id: 'generation', label: '生成' },
  { id: 'file', label: '文件' },
  { id: 'map', label: '地图' },
] as const;

export const tools = [
  {
    id: 'color-converter',
    path: '/color-converter',
    category: 'conversion',
    title: '颜色转换',
    summary: 'HEX、RGB、HSL、HSV、CMYK 互转，并实时预览颜色。',
    status: '已可用',
    icon: Palette,
  },
  {
    id: 'timestamp-converter',
    path: '/timestamp-converter',
    category: 'conversion',
    title: '时间戳转换',
    summary: '秒、毫秒时间戳与本地时间、UTC、ISO 时间互转。',
    status: '已可用',
    icon: Clock3,
  },
  {
    id: 'json-formatter',
    path: '/json-formatter',
    category: 'formatting',
    title: 'JSON 格式化',
    summary: 'JSON 校验、格式化、压缩，并显示解析错误。',
    status: '已可用',
    icon: Braces,
  },
  {
    id: 'url-codec',
    path: '/url-codec',
    category: 'encoding',
    title: 'URL 编解码',
    summary: 'URL encode/decode，并解析 Query 参数。',
    status: '已可用',
    icon: LinkIcon,
  },
  {
    id: 'base64-codec',
    path: '/base64-codec',
    category: 'encoding',
    title: 'Base64 编解码',
    summary: 'UTF-8 文本 Base64 编码和解码。',
    status: '已可用',
    icon: Binary,
  },
  {
    id: 'css-unit-converter',
    path: '/css-unit-converter',
    category: 'conversion',
    title: 'CSS 单位换算',
    summary: 'px、rem、em、vw、vh 常用单位换算。',
    status: '已可用',
    icon: Ruler,
  },
  {
    id: 'gradient-generator',
    path: '/gradient-generator',
    category: 'css',
    title: 'Gradient 生成器',
    summary: '可视化生成 linear-gradient CSS。',
    status: '已可用',
    icon: Paintbrush,
  },
  {
    id: 'regex-tester',
    path: '/regex-tester',
    category: 'formatting',
    title: 'Regex 测试器',
    summary: '测试正则表达式，查看匹配结果和捕获组。',
    status: '已可用',
    icon: Regex,
  },
  {
    id: 'uuid-generator',
    path: '/uuid-generator',
    category: 'generation',
    title: 'UUID 生成器',
    summary: '批量生成 UUID v4，支持大小写输出。',
    status: '已可用',
    icon: KeyRound,
  },
  {
    id: 'hash-generator',
    path: '/hash-generator',
    category: 'encoding',
    title: 'Hash 生成器',
    summary: '生成 SHA-1、SHA-256、SHA-384、SHA-512 文本摘要。',
    status: '已可用',
    icon: Fingerprint,
  },
  {
    id: 'cad-viewer',
    path: '/cad-viewer',
    category: 'file',
    title: 'CAD 文件查看器',
    summary: '上传 DXF 文件，在浏览器中预览常见 CAD 实体。',
    status: '已可用',
    icon: FileSearch,
  },
  {
    id: 'botw-map',
    path: '/botw-map',
    category: 'map',
    title: '旷野之息地图',
    summary: '基于 Leaflet 的地图图片漫游、缩放、坐标读取和地点标注。',
    status: '已可用',
    icon: MapPinned,
  },
  {
    id: 'yaml-formatter',
    path: '/yaml-formatter',
    category: 'formatting',
    title: 'YAML / JSON 互转',
    summary: 'YAML 校验、格式化，支持与 JSON 互相转换。',
    status: '已可用',
    icon: FileJson,
  },
  {
    id: 'jwt-parser',
    path: '/jwt-parser',
    category: 'encoding',
    title: 'JWT 解析器',
    summary: '解析 JWT Header、Payload，展示时间字段可读时间。',
    status: '已可用',
    icon: ShieldCheck,
  },
  {
    id: 'string-toolbox',
    path: '/string-toolbox',
    category: 'formatting',
    title: '字符串工具箱',
    summary: '大小写转换、驼峰/短横线/下划线互转、去重行、字符统计。',
    status: '已可用',
    icon: CaseSensitive,
  },
  {
    id: 'json-to-ts',
    path: '/json-to-ts',
    category: 'formatting',
    title: 'JSON 转 TypeScript',
    summary: '根据 JSON 示例生成 TypeScript interface / type 定义。',
    status: '已可用',
    icon: Braces,
  },
  {
    id: 'markdown-preview',
    path: '/markdown-preview',
    category: 'formatting',
    title: 'Markdown 预览',
    summary: '左侧编辑 Markdown，右侧实时预览，可复制源码和 HTML。',
    status: '已可用',
    icon: Eye,
  },
  {
    id: 'cron-parser',
    path: '/cron-parser',
    category: 'conversion',
    title: 'Cron 表达式解析',
    summary: '解析 Cron 表达式字段含义，预览最近执行时间。',
    status: '已可用',
    icon: Clock3,
  },
  {
    id: 'xml-formatter',
    path: '/xml-formatter',
    category: 'formatting',
    title: 'XML 格式化',
    summary: 'XML 校验、格式化、压缩，支持 XML ↔ JSON 互转。',
    status: '已可用',
    icon: FileCode,
  },
] as const;
