import { Binary, Braces, Clock3, Fingerprint, KeyRound, LinkIcon, Palette, Paintbrush, Regex, Ruler } from "lucide-react";

export const toolCategories = [
  { id: "all", label: "全部" },
  { id: "conversion", label: "转换" },
  { id: "encoding", label: "编码" },
  { id: "formatting", label: "格式化" },
  { id: "css", label: "CSS" },
  { id: "generation", label: "生成" },
] as const;

export const tools = [
  {
    id: "color-converter",
    path: "/color-converter",
    category: "conversion",
    title: "颜色转换",
    summary: "HEX、RGB、HSL、HSV、CMYK 互转，并实时预览颜色。",
    status: "已可用",
    icon: Palette,
  },
  {
    id: "timestamp-converter",
    path: "/timestamp-converter",
    category: "conversion",
    title: "时间戳转换",
    summary: "秒、毫秒时间戳与本地时间、UTC、ISO 时间互转。",
    status: "已可用",
    icon: Clock3,
  },
  {
    id: "json-formatter",
    path: "/json-formatter",
    category: "formatting",
    title: "JSON 格式化",
    summary: "JSON 校验、格式化、压缩，并显示解析错误。",
    status: "已可用",
    icon: Braces,
  },
  {
    id: "url-codec",
    path: "/url-codec",
    category: "encoding",
    title: "URL 编解码",
    summary: "URL encode/decode，并解析 Query 参数。",
    status: "已可用",
    icon: LinkIcon,
  },
  {
    id: "base64-codec",
    path: "/base64-codec",
    category: "encoding",
    title: "Base64 编解码",
    summary: "UTF-8 文本 Base64 编码和解码。",
    status: "已可用",
    icon: Binary,
  },
  {
    id: "css-unit-converter",
    path: "/css-unit-converter",
    category: "conversion",
    title: "CSS 单位换算",
    summary: "px、rem、em、vw、vh 常用单位换算。",
    status: "已可用",
    icon: Ruler,
  },
  {
    id: "gradient-generator",
    path: "/gradient-generator",
    category: "css",
    title: "Gradient 生成器",
    summary: "可视化生成 linear-gradient CSS。",
    status: "已可用",
    icon: Paintbrush,
  },
  {
    id: "regex-tester",
    path: "/regex-tester",
    category: "formatting",
    title: "Regex 测试器",
    summary: "测试正则表达式，查看匹配结果和捕获组。",
    status: "已可用",
    icon: Regex,
  },
  {
    id: "uuid-generator",
    path: "/uuid-generator",
    category: "generation",
    title: "UUID 生成器",
    summary: "批量生成 UUID v4，支持大小写输出。",
    status: "已可用",
    icon: KeyRound,
  },
  {
    id: "hash-generator",
    path: "/hash-generator",
    category: "encoding",
    title: "Hash 生成器",
    summary: "生成 SHA-1、SHA-256、SHA-384、SHA-512 文本摘要。",
    status: "已可用",
    icon: Fingerprint,
  },
] as const;
